### ISSUE TITLE
can't import from previous release

### ISSUE THREAD

**Issue by tieu1991** [Helium314/DejaVu#1]
if you install over the pre-alpha release it crashes. So I tried to do a clean install and use the importer to import the rf.db from the previous release. This give this error :

Error importing database : Can't downgrade database from version 5 to 4

**Comment by Helium314** [comment]
I did have some different db format for a while, which turned out to be a bad idea, but I though I had reverted this prior to the pre-alpha. I'll have a look

**Comment by Helium314** [comment]
Ok, I (obviously, hence the issue) did not revert the change before the pre-alpha.
Honestly I didn't really expect anyone to use this, so thanks for trying and sorry for the inconvenience.

Anyway, the easiest solution should be changing the DB version from 5 to 4, e.g. using [DB browser for SQLite](https://sqlitebrowser.org/): Just go to pragmas, change `User Version` to 4 and click save.

**Comment by tieu1991** [comment]
Thank you very much. It worked.
